/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kayipcheung' at '12/21/16 11:23 AM' with Gradle 3.2.1
 *
 * @author kayipcheung, @date 12/21/16 11:23 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
